USE controle_estoque;


INSERT INTO perfil (nome, descricao) VALUES
('Administrador', 'Acesso total ao sistema'),
('Gerente', 'Responsável pela gestão do estoque'),
('Estoquista', 'Realiza lançamentos e conferências'),
('Vendedor', 'Consulta produtos e saldos'),
('Supervisor', 'Acompanha movimentações'),
('Analista', 'Analisa dados do estoque'),
('Operador', 'Executa rotinas operacionais'),
('Financeiro', 'Consulta valores e relatórios'),
('Conferente', 'Confere entradas e saídas'),
('Consulta', 'Acesso apenas para visualização');


INSERT INTO tipo_movimentacao (nome, descricao) VALUES
('ENTRADA', 'Entrada de produtos no estoque'),
('SAIDA', 'Saída de produtos do estoque'),
('AJUSTE', 'Ajuste de quantidade no estoque'),
('DEVOLUCAO', 'Devolução de mercadoria'),
('TRANSFERENCIA', 'Transferência entre setores');


INSERT INTO usuario (nome, email, senha, ativo, id_perfil) VALUES
('Daniel', 'daniel@empresa.com', 'Adm@123', TRUE, 1),
('Maria Santos', 'maria.santos@empresa.com', 'Ger@123', TRUE, 2),
('Joao Pereira', 'joao.pereira@empresa.com', 'Est@123', TRUE, 3),
('Ana Costa', 'ana.costa@empresa.com', 'Ven@123', TRUE, 4),
('Pedro Alves', 'pedro.alves@empresa.com', 'Sup@123', FALSE, 5),
('Camila Rocha', 'camila.rocha@empresa.com', 'Ana@123', TRUE, 6),
('Lucas Ferreira', 'lucas.ferreira@empresa.com', 'Ope@123', TRUE, 7),
('Juliana Lima', 'juliana.lima@empresa.com', 'Fin@123', FALSE, 8),
('Rafael Gomes', 'rafael.gomes@empresa.com', 'Con@123', TRUE, 9),
('Fernanda Souza', 'fernanda.souza@empresa.com', 'Vis@123', TRUE, 10),
('Bruno Martins', 'bruno.martins@empresa.com', 'Adm@456', TRUE, 1),
('Patricia Oliveira', 'patricia.oliveira@empresa.com', 'Ger@456', TRUE, 2),
('Gustavo Ribeiro', 'gustavo.ribeiro@empresa.com', 'Est@456', FALSE, 3),
('Carla Mendes', 'carla.mendes@empresa.com', 'Ven@456', TRUE, 4),
('Thiago Barros', 'thiago.barros@empresa.com', 'Sup@456', TRUE, 5),
('Aline Nascimento', 'aline.nascimento@empresa.com', 'Ana@456', TRUE, 6),
('Marcos Teixeira', 'marcos.teixeira@empresa.com', 'Ope@456', FALSE, 7),
('Bianca Castro', 'bianca.castro@empresa.com', 'Fin@456', TRUE, 8),
('Felipe Araujo', 'felipe.araujo@empresa.com', 'Con@456', TRUE, 9),
('Larissa Pinto', 'larissa.pinto@empresa.com', 'Vis@456', FALSE, 10);

-- PRODUTOS
INSERT INTO produto (nome, descricao, preco, quantidade_estoque, ativo) VALUES
('Notebook Lenovo', 'Notebook corporativo 14 polegadas', 3899.90, 12, TRUE),
('Mouse Sem Fio', 'Mouse óptico sem fio', 79.90, 150, TRUE),
('Teclado Mecânico', 'Teclado mecânico ABNT2', 249.90, 60, TRUE),
('Monitor 24"', 'Monitor LED Full HD', 899.90, 30, TRUE),
('Impressora Laser', 'Impressora monocromática', 1299.90, 8, TRUE),
('Cabo HDMI', 'Cabo HDMI 2 metros', 29.90, 200, TRUE),
('Headset Gamer', 'Headset com microfone', 199.90, 45, TRUE),
('Webcam HD', 'Webcam para videoconferência', 159.90, 40, TRUE),
('SSD 480GB', 'Unidade de estado sólido', 299.90, 70, TRUE),
('Pendrive 64GB', 'Memória USB 64GB', 49.90, 180, TRUE),
('Cadeira Ergonômica', 'Cadeira de escritório ergonômica', 899.90, 20, TRUE),
('Mesa Escritório', 'Mesa com gaveta', 650.00, 15, TRUE),
('Roteador Wi-Fi', 'Roteador dual band', 229.90, 35, TRUE),
('Switch 8 Portas', 'Switch de rede 8 portas', 189.90, 25, TRUE),
('Nobreak 1200VA', 'Nobreak para proteção elétrica', 749.90, 18, TRUE),
('Tablet 10"', 'Tablet para uso corporativo', 1599.90, 10, TRUE),
('Carregador USB-C', 'Carregador rápido USB-C', 89.90, 120, TRUE),
('Adaptador USB', 'Adaptador USB 3.0', 39.90, 90, TRUE),
('Fone de Ouvido', 'Fone estéreo com fio', 59.90, 110, TRUE),
('Projetor', 'Projetor multimídia', 2199.90, 6, FALSE),
('Gaveteiro', 'Gaveteiro móvel com rodas', 299.90, 22, TRUE),
('Cadeira Plástica', 'Cadeira empilhável', 49.90, 300, TRUE),
('Suporte Monitor', 'Suporte ajustável para monitor', 139.90, 55, TRUE),
('Filtro de Linha', 'Filtro com proteção', 69.90, 140, TRUE),
('Telefone Sem Fio', 'Telefone para escritório', 179.90, 28, TRUE),
('Scanner', 'Scanner de documentos', 1099.90, 7, TRUE),
('HD Externo 1TB', 'Disco rígido externo', 349.90, 32, TRUE),
('Luminária LED', 'Luminária de mesa LED', 99.90, 75, TRUE),
('Armario Aco', 'Armário de aço com 2 portas', 799.90, 11, TRUE),
('Caixa Organizadora', 'Caixa plástica organizadora', 24.90, 210, TRUE);

-- MOVIMENTAÇÕES DE ESTOQUE
INSERT INTO movimentacao_estoque (quantidade, observacao, id_tipo_movimentacao, id_produto, id_usuario) VALUES
(5, 'Recebimento inicial de notebook', 1, 1, 1),
(20, 'Entrada de mouse para reposição', 1, 2, 2),
(10, 'Venda de teclados para setor administrativo', 2, 3, 3),
(3, 'Saída para sala de reunião', 2, 4, 4),
(2, 'Entrada de impressoras por compra', 1, 5, 5),
(15, 'Reposição de cabos HDMI', 1, 6, 6),
(8, 'Saída de headsets para equipe de suporte', 2, 7, 7),
(4, 'Entrada de webcams novas', 1, 8, 8),
(6, 'Ajuste após inventário físico', 3, 9, 9),
(30, 'Entrada de pendrives em lote', 1, 10, 10),
(2, 'Saída de cadeiras para novo setor', 2, 11, 11),
(1, 'Entrada de mesa adicional', 1, 12, 12),
(7, 'Reposição de roteadores', 1, 13, 13),
(3, 'Saída de switch para filial', 5, 14, 14),
(2, 'Transferência de nobreak para outra unidade', 5, 15, 15),
(4, 'Devolução de tablets não utilizados', 4, 16, 16),
(25, 'Entrada de carregadores USB-C', 1, 17, 17),
(10, 'Reposição complementar de mouse sem fio', 1, 2, 1),
(10, 'Ajuste de adaptadores USB', 3, 18, 18),
(12, 'Saída de fones para treinamento', 2, 19, 19),
(5, 'Saída de gaveteiros para escritório', 2, 21, 1),
(15, 'Entrada de cadeiras plásticas', 1, 22, 2),
(6, 'Transferência de suportes de monitor', 5, 23, 3),
(8, 'Saída de filtros de linha', 2, 24, 4),
(4, 'Devolução de telefones sem fio', 4, 25, 5),
(2, 'Entrada de scanners', 1, 26, 6),
(9, 'Saída de HD externo para equipe técnica', 2, 27, 7),
(11, 'Entrada de luminárias LED', 1, 28, 8),
(3, 'Ajuste de armários de aço', 3, 29, 9),
(40, 'Entrada de caixas organizadoras', 1, 30, 10),
(1, 'Saída de notebook para teste', 2, 1, 11),
(5, 'Entrada de mouse sem fio complementar', 1, 2, 12),
(2, 'Transferência de teclado mecânico entre setores', 5, 3, 13),
(1, 'Ajuste de monitor após conferência', 3, 4, 14),
(3, 'Devolução de impressora após manutenção', 4, 5, 15);